import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { useBoolean } from "@chakra-ui/react";
import { api } from "y/utils/api";
import CaptionCarousel from "./carousel";
import Navbar from "./navbar";
import CardTravel from "./card";
import Maps from "./map";
// import { Input } from "postcss";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const [flag, setFlag] = useBoolean();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <CaptionCarousel />
      <CardTravel />
      <Maps />
    </>
  );
};

export default Home;
