import { type NextPage } from "next";
import Head from "next/head";

import CaptionCarousel from "./carousel";
import Navbar from "./navbar";
import CardTravel from "./card";
import Maps from "./map";
// import { Input } from "postcss";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <CaptionCarousel />
      <CardTravel />
      <Maps />
    </>
  );
};

export default Home;
